# Generated by Django 4.1 on 2024-03-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=120)),
                ('modelo', models.CharField(max_length=120)),
                ('capacidade_watt', models.IntegerField()),
                ('tensao_entrada_max', models.IntegerField()),
                ('tensao_saida', models.IntegerField()),
                ('eficiencia', models.IntegerField()),
                ('tipo', models.CharField(choices=[('string', 'String'), ('central', 'Central'), ('micro', 'Micro')], max_length=7)),
                ('compatibilidade', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PainelSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=120)),
                ('modelo', models.CharField(max_length=120)),
                ('capacidade_watt', models.IntegerField()),
            ],
        ),
    ]
