# Generated by Django 4.1 on 2024-03-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_propriedade'),
        ('usinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painel_quantidade', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('inversor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usinas.inversor')),
                ('painel_solar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usinas.painelsolar')),
            ],
        ),
    ]
