# Generated by Django 4.1 on 2024-03-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_propriedade'),
        ('usinas', '0002_usina'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usina',
            new_name='Modelousina',
        ),
    ]
