# Generated by Django 4.1 on 2024-07-10 02:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_cep', message='CEP deve seguir o formato 12345-678.', regex='^\\d{5}-\\d{3}$')])),
                ('ponto_referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone_fixo', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_telefone_fixo', message='Telefone fixo deve seguir o formato (xx) xxxx-xxxx ou (xx) xxxxx-xxxx.', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')])),
                ('numero_celular', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_celular', message='Número de celular deve seguir o formato (xx) xxxxx-xxxx.', regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')])),
                ('email', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator(code='invalid_email', message='E-mail deve ser válido.')])),
                ('tipo_cliente', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=50)),
                ('cnpj', models.CharField(blank=True, default=None, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cnpj', message='CNPJ deve seguir o formato 12.345.678/9012-34.', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')])),
                ('cpf', models.CharField(blank=True, default=None, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cpf', message='CPF deve seguir o formato 123.456.789-01.', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('titularidade', models.BooleanField(default=True)),
                ('bairro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.bairro')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rateio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('endereco', models.CharField(max_length=200)),
                ('conta_contrato', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Nome da Propriedade')),
                ('propriedade', models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('industrial', 'Industrial'), ('fazenda', 'Fazenda')], max_length=50, verbose_name='Tipo de Propriedade')),
                ('area_instalacao', models.IntegerField(verbose_name='Área de Instalação')),
                ('consumo', models.IntegerField(verbose_name='Consumo Mensal')),
                ('tipo_telhado', models.CharField(choices=[('inclinado', 'Telhado Inclinado'), ('plano', 'Telhado Plano'), ('metal', 'Telhado de Metal'), ('estrutura elevada', 'Estrutura Elevada')], max_length=50, verbose_name='Tipo de Telhado')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('detalhes', models.TextField()),
                ('data_interacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='clientes.cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.estado'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.estado'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cidade'),
        ),
    ]
