# Generated by Django 4.1 on 2024-01-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Clientes',
        ),
    ]
