# Generated by Django 5.0.1 on 2024-01-11 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('Cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cidade')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.bairro'),
        ),
    ]
