# Generated by Django 5.0.1 on 2024-01-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_bairro_alter_cliente_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
