# Generated by Django 5.0.1 on 2024-01-11 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_cliente_bairro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bairro',
            old_name='Cidade',
            new_name='cidade',
        ),
    ]
