# Generated by Django 4.1 on 2024-01-15 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_alter_cliente_bairro_alter_cliente_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
