# Generated by Django 4.1 on 2024-02-08 01:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_alter_cliente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='cidade', chained_model_field='cidade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.bairro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cnpj', message='CNPJ deve seguir o formato 12.345.678/9012-34.', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cpf', message='CPF deve seguir o formato 123.456.789-01.', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')]),
        ),
    ]
