# Generated by Django 4.1 on 2024-03-16 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_propriedade'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propriedade',
            table='local_instalaao',
        ),
    ]
