# Generated by Django 4.1 on 2024-03-16 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0025_alter_propriedade_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propriedade',
            table='local_instalacao',
        ),
    ]
