# Generated by Django 4.1 on 2024-03-16 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0026_alter_propriedade_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propriedade',
            table=None,
        ),
    ]
