# Generated by Django 4.1 on 2024-03-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0027_alter_propriedade_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='propriedade',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('industrial', 'Industrial'), ('fazenda', 'Fazenda')], max_length=50, verbose_name='Tipo de Propriedade'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='tipo_telhado',
            field=models.CharField(choices=[('inclinado', 'Telhado Inclinado'), ('plano', 'Telhado Plano'), ('metal', 'Telhado de Metal'), ('estrutura elevada', 'Estrutura Elevada')], max_length=50, verbose_name='Tipo de Telhado'),
        ),
    ]
