# Generated by Django 4.1 on 2024-03-25 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0028_alter_propriedade_propriedade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rateio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('endereco', models.CharField(max_length=200)),
                ('conta_contrato', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
