# Generated by Django 4.1 on 2024-04-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0029_rateio'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='nome',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Nome da Propriedade'),
        ),
    ]
