# Generated by Django 4.1 on 2024-06-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0030_propriedade_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='titularidade',
            field=models.BooleanField(default=False),
        ),
    ]
