# Generated by Django 4.1 on 2024-06-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0031_cliente_titularidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='titularidade',
            field=models.BooleanField(default=True),
        ),
    ]
