# Generated by Django 4.1 on 2024-03-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0029_rateio'),
        ('usinas', '0003_rename_usina_modelousina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo', models.IntegerField()),
                ('energia_gerada', models.IntegerField()),
                ('numero_painel', models.IntegerField()),
                ('numero_inversor', models.IntegerField()),
                ('espaco_disponivel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_garantia', models.IntegerField()),
                ('valor_orcamento', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('inversor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usinas.inversor')),
                ('painel_solar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usinas.painelsolar')),
            ],
        ),
    ]
