# Generated by Django 4.1 on 2024-03-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('aberto', 'Em Aberto'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aberto', max_length=10),
        ),
    ]
