# Generated by Django 4.1 on 2024-04-13 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0030_propriedade_nome'),
        ('contratos', '0002_orcamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='propriedade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.propriedade'),
        ),
    ]
