# Generated by Django 4.1 on 2024-04-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_orcamento_propriedade'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='info_adicionais',
            field=models.TextField(blank=True, null=True, verbose_name='Informações Adicionais'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_unitario_painel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor Unitário do Painel'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_unitario_usina',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor Unitário da Usina'),
        ),
    ]
