# Generated by Django 4.1 on 2024-06-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_orcamento_info_adicionais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='titularidade',
            field=models.BooleanField(default=True),
        ),
    ]
