# Generated by Django 4.1 on 2024-06-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_orcamento_titularidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='valor_unitario_usina',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_unitario_inversor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor Unitário da Inversor'),
        ),
    ]
