# Generated by Django 4.1 on 2024-06-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_remove_orcamento_valor_unitario_usina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='valor_maodeobra',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor mao de obra'),
        ),
    ]
