# Generated by Django 4.1 on 2024-06-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_orcamento_valor_maodeobra'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='orcamento',
            name='tipos_pagamento',
            field=models.ManyToManyField(related_name='orcamentos', to='contratos.tipopagamento'),
        ),
    ]
