# Generated by Django 4.1 on 2024-06-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_tipopagamento_orcamento_tipos_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='tempo_garantia',
            field=models.DateField(),
        ),
    ]
